Series 
Создайте Series, содержащий цифры от 10 до 1000 ( data = pd.Series(list(range(10, 1001))) ). Что выведет на экран следующий код: print(data.loc[10] + data.loc[23] - data.loc[245] + data.iloc[122])?

In [1]:
import pandas as pd
data = pd.Series(list(range(10, 1001)))
print(data.loc[10] + data.loc[23] - data.loc[245] + data.iloc[122])

-70

In [2]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
display(df)

   col1  col2
0     1     3
1     2     4

In [3]:
df = pd.DataFrame([ [1,2,3], [2,3,4] ],
                  columns = ['foo', 'bar', 'baz'], 
                  index = ['foobar', 'foobaz'])
display(df)

        foo  bar  baz
foobar    1    2    3
foobaz    2    3    4

In [ ]:
pd.read_csv('Полный_путь_к_файлу/название_файла.csv')

pandas.read_csv(filepath_or_buffer, sep=', ', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)

encoding : str, optional
Encoding to use for UTF when reading/writing (ex. ‘utf-8’). List of Python standard encodings .

dialect : str or csv.Dialect, optional
If provided, this parameter will override values (default or not) for the following parameters: delimiter, doublequote, escapechar, skipinitialspace, quotechar, and quoting. If it is necessary to override values, a ParserWarning will be issued. See csv.Dialect documentation for more details.

squeeze : bool, default False
If the parsed data only contains one column then return a Series.

In [4]:
import pandas as pd

football = pd.read_csv('C:/Users/Vika/Notebooks Python/data_sf.csv')
display(football.head())

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13

In [5]:
display(football.tail(7))

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
12890,13119,J. Young,18,Scotland,Swindon Town,450000,1000,ST,28,47,...,58,50,15,17,14,11,15,12,12,11
12891,13120,D. Walsh,18,Republic of Ireland,Waterford FC,60000,1000,RB,22,23,...,38,43,44,47,53,9,10,9,11,13
12892,13121,J. Lundstram,19,England,Crewe Alexandra,1100000,1000,CM,34,38,...,43,45,40,48,47,10,13,7,8,9
12893,13122,N. Christoffersson,19,Sweden,Trelleborgs FF,60000,1000,ST,23,52,...,43,42,22,15,19,10,9,9,5,12
12894,13123,B. Worman,16,England,Cambridge United,60000,1000,ST,25,40,...,55,41,32,13,11,6,5,10,6,13
12895,13124,D. Walker-Rice,17,England,Tranmere Rovers,60000,1000,RW,44,50,...,50,46,20,25,27,14,6,14,8,9
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9

In [6]:
display(football.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 42 columns):
Unnamed: 0         12897 non-null int64
Name               12897 non-null object
Age                12897 non-null int64
Nationality        12897 non-null object
Club               12897 non-null object
Value              12897 non-null int64
Wage               12897 non-null int64
Position           12897 non-null object
Crossing           12897 non-null int64
Finishing          12897 non-null int64
HeadingAccuracy    12897 non-null int64
ShortPassing       12897 non-null int64
Volleys            12897 non-null int64
Dribbling          12897 non-null int64
Curve              12897 non-null int64
FKAccuracy         12897 non-null int64
LongPassing        12897 non-null int64
BallControl        12897 non-null int64
Acceleration       12897 non-null int64
SprintSpeed        12897 non-null int64
Agility            12897 non-null int64
Reactions          12897 non-null int64
Balance            12897 non-null int64
ShotPower          12897 non-null int64
Jumping            12897 non-null int64
Stamina            12897 non-null int64
Strength           12897 non-null int64
LongShots          12897 non-null int64
Aggression         12897 non-null int64
Interceptions      12897 non-null int64
Positioning        12897 non-null int64
Vision             12897 non-null int64
Penalties          12897 non-null int64
Composure          12897 non-null int64
Marking            12897 non-null int64
StandingTackle     12897 non-null int64
SlidingTackle      12897 non-null int64
GKDiving           12897 non-null int64
GKHandling         12897 non-null int64
GKKicking          12897 non-null int64
GKPositioning      12897 non-null int64
GKReflexes         12897 non-null int64
dtypes: int64(38), object(4)
memory usage: 4.1+ MB

None

In [7]:
football.describe()

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,...,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,...,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,...,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,...,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,...,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,...,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,...,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,...,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [8]:
football.describe(include = ['object'])

                Name Nationality             Club Position
count          12897       12897            12897    12897
unique         12326         156              650       27
top     J. Rodríguez     England  Shonan Bellmare       GK
freq               9        1368               30     1641

In [9]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df.describe())

            foo       bar       baz
count  2.000000  2.000000  2.000000
mean   1.500000  2.500000  3.500000
std    0.707107  0.707107  0.707107
min    1.000000  2.000000  3.000000
25%    1.250000  2.250000  3.250000
50%    1.500000  2.500000  3.500000
75%    1.750000  2.750000  3.750000
max    2.000000  3.000000  4.000000

In [10]:
df = pd.DataFrame([[i,i+1.2,i+2, 'hi'] for i in range(10)],
                  columns = ['foo', 'bar', 'baz', 'foobar'])
df.mean()

foo    4.5
bar    5.7
baz    6.5
dtype: float64

In [11]:
df = pd.DataFrame([[i,i+1.2,i+2, 'hi'] for i in range(10)],
                  columns = ['foo', 'bar', 'baz', 'foobar'])
display(df)

   foo   bar  baz foobar
0    0   1.2    2     hi
1    1   2.2    3     hi
2    2   3.2    4     hi
3    3   4.2    5     hi
4    4   5.2    6     hi
5    5   6.2    7     hi
6    6   7.2    8     hi
7    7   8.2    9     hi
8    8   9.2   10     hi
9    9  10.2   11     hi

In [13]:
df = pd.DataFrame([[i,i+1.2,i+2, 'hi'] for i in range(10)],
                  columns = ['foo', 'bar', 'baz', 'foobar'])

df.bar

0     1.2
1     2.2
2     3.2
3     4.2
4     5.2
5     6.2
6     7.2
7     8.2
8     9.2
9    10.2
Name: bar, dtype: float64

In [14]:
df['foo']

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: foo, dtype: int64

In [15]:
df = pd.DataFrame([[i,i+1.2,i+2, 'hi'] for i in range(10)],
                  columns = ['foo', 'bar', 'baz', 'foobar'])
df.bar.mean()

5.7

In [18]:
football.Age.mean()

24.795378770256647

In [19]:
football.Composure.count()

12897

In [20]:
football.ShortPassing.std()

14.740435689517149

In [21]:
football.Wage.sum()

96954000

In [22]:
football.Value.min()

0

In [2]:
import pandas as pd

football = pd.read_csv('C:/Users/Vika/Notebooks Python/data_sf.csv')
football[football.Age > 20]

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
5,5,E. Hazard,27,Belgium,Chelsea,93000000,340000,LF,81,84,...,86,91,34,27,22,11,12,6,8,8
6,6,L. Modrić,32,Croatia,Real Madrid,67000000,420000,RCM,86,72,...,82,84,60,76,73,13,9,7,14,9
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
8,8,Sergio Ramos,32,Spain,Real Madrid,51000000,380000,RCB,66,60,...,75,82,87,92,91,11,8,9,7,11
9,9,J. Oblak,25,Slovenia,Atlético Madrid,68000000,94000,GK,13,11,...,11,70,27,12,18,86,92,78,88,89
10,10,R. Lewandowski,29,Poland,FC Bayern München,77000000,205000,ST,62,91,...,88,86,34,42,19,15,6,12,8,10
11,11,T. Kroos,28,Germany,Real Madrid,76500000,355000,LCM,88,76,...,73,85,72,79,69,10,11,13,7,10
12,12,D. Godín,32,Uruguay,Atlético Madrid,44000000,125000,CB,55,42,...,50,82,90,89,89,6,8,15,5,15
13,13,David Silva,32,Spain,Manchester City,60000000,285000,LCM,84,76,...,75,93,59,53,29,6,15,7,6,12
14,14,N. Kanté,27,France,Chelsea,63000000,225000,LDM,68,65,...,54,85,90,91,85,15,12,10,7,10
15,15,P. Dybala,24,Argentina,Juventus,89000000,205000,LF,82,84,...,86,84,23,20,20,5,4,4,5,8
16,16,H. Kane,24,England,Tottenham Hotspur,83500000,205000,ST,75,94,...,90,89,56,36,38,8,10,11,14,11
17,17,A. Griezmann,27,France,Atlético Madrid,78000000,145000,CAM,82,90,...,79,87,59,47,48,14,8,14,13,14
18,18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK,15,14,...,25,69,25,13,10,87,85,88,85,90
19,19,T. Courtois,26,Belgium,Real Madrid,53500000,240000,GK,14,14,...,27,66,20,18,16,85,91,72,86,88
20,20,Sergio Busquets,29,Spain,FC Barcelona,51500000,315000,CDM,62,67,...,60,90,90,86,80,5,8,13,9,13
21,21,E. Cavani,31,Uruguay,Paris Saint-Germain,60000000,200000,LS,70,89,...,85,82,52,45,39,12,5,13,13,10
22,22,M. Neuer,32,Germany,FC Bayern München,38000000,130000,GK,15,13,...,47,70,17,10,11,90,86,91,87,87
23,23,S. Agüero,30,Argentina,Manchester City,64500000,300000,ST,70,93,...,83,90,30,20,12,13,15,6,11,14
24,24,G. Chiellini,33,Italy,Juventus,27000000,215000,LCB,58,33,...,50,84,93,93,90,3,3,2,4,3
26,26,M. Salah,26,Egypt,Liverpool,69500000,255000,RM,78,90,...,61,91,38,43,41,14,14,9,11,14
27,27,Casemiro,26,Brazil,Real Madrid,59500000,285000,CDM,52,59,...,66,84,88,90,87,13,14,16,12,12
28,28,J. Rodríguez,26,Colombia,FC Bayern München,69500000,315000,LAM,90,83,...,81,87,52,41,44,15,15,15,5,14
29,29,L. Insigne,27,Italy,Napoli,62000000,165000,LW,86,77,...,61,83,51,24,22,8,4,14,9,10
30,30,Isco,26,Spain,Real Madrid,73500000,315000,LW,75,79,...,76,86,60,64,51,10,8,12,15,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12699,12928,J. Heaton,21,England,St. Mirren,60000,1000,CB,26,21,...,38,40,57,56,54,8,10,9,7,10
12701,12930,D. Schwizer,22,Switzerland,FC Thun,60000,2000,CAM,41,32,...,48,39,32,34,44,10,11,8,8,11
12702,12931,Cao Sheng,23,China PR,Shandong Luneng TaiShan FC,50000,2000,RW,46,53,...,47,44,31,20,29,13,8,8,12,9
12704,12933,Zhu Zhengyu,23,China PR,Guizhou Hengfeng FC,50000,2000,RM,46,45,...,50,45,41,22,28,13,15,6,12,8
12711,12940,Han Zilong,24,China PR,Changchun Yatai FC,40000,1000,LM,52,40,...,50,49,39,27,20,9,8,12,12,15
12719,12948,J. Miszczuk,27,Poland,Jagiellonia Białystok,20000,1000,GK,11,11,...,22,22,15,19,17,48,48,49,48,51
12720,12949,Chen Ji,21,China PR,Guizhou Hengfeng FC,50000,2000,LM,41,28,...,42,38,46,48,51,15,8,10,13,7
12721,12950,A. Mills,24,England,Östersunds FK,30000,1000,GK,20,14,...,22,30,13,16,17,51,46,45,49,51
12726,12955,Zhang Enge,21,China PR,Shanghai SIPG FC,40000,1000,CB,21,16,...,38,42,47,54,50,7,13,5,14,15
12728,12957,M. Alvir,24,Croatia,SK Slavia Praha,40000,1000,CM,45,32,...,41,40,34,41,40,13,13,5,15,10
12737,12966,A. Suzuki,31,Japan,Yokohama F. Marinos,20000,1000,GK,11,9,...,18,31,13,10,14,49,48,54,52,54
12746,12975,Teng Shangkun,27,China PR,Tianjin TEDA FC,20000,1000,GK,10,8,...,17,58,28,10,13,46,56,55,45,53
12749,12978,M. Mansour,26,Saudi Arabia,Al Batin,30000,2000,LB,36,18,...,33,37,45,54,54,10,8,6,13,13
12756,12985,Gao Dalun,21,China PR,Jiangsu Suning FC,40000,2000,ST,26,50,...,55,42,30,18,16,10,9,10,11,11
12762,12991,O. Dzonlagic,23,Switzerland,FC Thun,50000,2000,RM,53,52,...,50,42,25,27,27,13,8,7,14,9
12764,12993,Liu Yi,21,China PR,Tianjin Quanjian FC,40000,2000,CDM,40,34,...,41,37,50,52,50,11,15,14,10,8
12767,12996,Sun Qibin,26,China PR,Tianjin Quanjian FC,20000,2000,GK,14,7,...,12,30,46,11,10,50,46,51,48,50
12777,13006,Kwon Ki Pyo,21,Korea Republic,Pohang Steelers,50000,1000,ST,33,57,...,63,47,46,17,14,13,7,14,12,5
12780,13009,M. Ichimaru,21,Japan,Gamba Osaka,60000,1000,CDM,39,27,...,37,47,47,39,51,7,9,10,12,14
12790,13019,M. Connor,21,Republic of Ireland,Waterford FC,50000,1000,GK,13,11,...,16,36,11,14,15,51,51,53,44,52
12791,13020,Zeng Qingshen,21,China PR,Vejle Boldklub,50000,1000,CM,36,28,...,39,44,30,44,38,13,10,9,11,11
12805,13034,Chen Zhao,21,China PR,Shanghai Greenland Shenhua FC,40000,1000,GK,10,9,...,12,29,18,13,11,50,52,50,40,53
12806,13035,R. Pasquel,22,Mexico,Deportivo Toluca,40000,2000,GK,11,8,...,14,36,12,10,10,54,53,47,40,56
12809,13038,K. Moesgaard,21,Denmark,Esbjerg fB,50000,1000,LM,47,44,...,40,45,26,27,26,10,6,9,10,6
12831,13060,Yin Congyao,21,China PR,Chongqing Dangdai Lifan FC SWM Team,50000,1000,CAM,40,37,...,43,56,54,36,43,8,11,7,14,11
12838,13067,D. Mackay,21,Scotland,Kilmarnock,30000,1000,GK,14,20,...,24,30,12,18,18,48,50,47,48,48
12857,13086,Wu Lei,21,China PR,Tianjin Quanjian FC,9000000,2000,LDM,52,29,...,46,39,52,40,49,8,15,11,8,5
12861,13090,Y. Uchimura,33,Japan,Hokkaido Consadole Sapporo,20000,1000,CAM,51,31,...,33,62,45,48,42,13,15,7,15,15
12870,13099,M. Hurst,22,Scotland,St. Johnstone FC,40000,1000,GK,19,15,...,29,28,12,15,16,45,49,50,50,45
12873,13102,K. Pilkington,44,England,Cambridge United,0,1000,GK,11,12,...,22,56,15,15,13,45,48,44,49,46

In [3]:
football[football.Age > football.Age.mean()]

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
5,5,E. Hazard,27,Belgium,Chelsea,93000000,340000,LF,81,84,...,86,91,34,27,22,11,12,6,8,8
6,6,L. Modrić,32,Croatia,Real Madrid,67000000,420000,RCM,86,72,...,82,84,60,76,73,13,9,7,14,9
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
8,8,Sergio Ramos,32,Spain,Real Madrid,51000000,380000,RCB,66,60,...,75,82,87,92,91,11,8,9,7,11
9,9,J. Oblak,25,Slovenia,Atlético Madrid,68000000,94000,GK,13,11,...,11,70,27,12,18,86,92,78,88,89
10,10,R. Lewandowski,29,Poland,FC Bayern München,77000000,205000,ST,62,91,...,88,86,34,42,19,15,6,12,8,10
11,11,T. Kroos,28,Germany,Real Madrid,76500000,355000,LCM,88,76,...,73,85,72,79,69,10,11,13,7,10
12,12,D. Godín,32,Uruguay,Atlético Madrid,44000000,125000,CB,55,42,...,50,82,90,89,89,6,8,15,5,15
13,13,David Silva,32,Spain,Manchester City,60000000,285000,LCM,84,76,...,75,93,59,53,29,6,15,7,6,12
14,14,N. Kanté,27,France,Chelsea,63000000,225000,LDM,68,65,...,54,85,90,91,85,15,12,10,7,10
17,17,A. Griezmann,27,France,Atlético Madrid,78000000,145000,CAM,82,90,...,79,87,59,47,48,14,8,14,13,14
18,18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK,15,14,...,25,69,25,13,10,87,85,88,85,90
19,19,T. Courtois,26,Belgium,Real Madrid,53500000,240000,GK,14,14,...,27,66,20,18,16,85,91,72,86,88
20,20,Sergio Busquets,29,Spain,FC Barcelona,51500000,315000,CDM,62,67,...,60,90,90,86,80,5,8,13,9,13
21,21,E. Cavani,31,Uruguay,Paris Saint-Germain,60000000,200000,LS,70,89,...,85,82,52,45,39,12,5,13,13,10
22,22,M. Neuer,32,Germany,FC Bayern München,38000000,130000,GK,15,13,...,47,70,17,10,11,90,86,91,87,87
23,23,S. Agüero,30,Argentina,Manchester City,64500000,300000,ST,70,93,...,83,90,30,20,12,13,15,6,11,14
24,24,G. Chiellini,33,Italy,Juventus,27000000,215000,LCB,58,33,...,50,84,93,93,90,3,3,2,4,3
26,26,M. Salah,26,Egypt,Liverpool,69500000,255000,RM,78,90,...,61,91,38,43,41,14,14,9,11,14
27,27,Casemiro,26,Brazil,Real Madrid,59500000,285000,CDM,52,59,...,66,84,88,90,87,13,14,16,12,12
28,28,J. Rodríguez,26,Colombia,FC Bayern München,69500000,315000,LAM,90,83,...,81,87,52,41,44,15,15,15,5,14
29,29,L. Insigne,27,Italy,Napoli,62000000,165000,LW,86,77,...,61,83,51,24,22,8,4,14,9,10
30,30,Isco,26,Spain,Real Madrid,73500000,315000,LW,75,79,...,76,86,60,64,51,10,8,12,15,6
31,31,C. Eriksen,26,Denmark,Tottenham Hotspur,73500000,205000,CAM,88,80,...,67,88,59,57,22,9,14,7,7,6
32,32,Coutinho,26,Brazil,FC Barcelona,69500000,340000,LW,79,79,...,70,85,55,54,47,12,7,9,14,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12164,12393,S. Ono,38,Japan,Hokkaido Consadole Sapporo,20000,1000,CM,56,50,...,58,67,38,40,31,8,10,9,6,11
12165,12394,M. Attiyah,26,Saudi Arabia,Ohod Club,80000,3000,LCM,42,56,...,57,41,59,36,21,10,16,15,15,10
12202,12431,Jin Hui,29,China PR,Beijing Renhe FC,70000,2000,ST,33,60,...,64,47,35,15,15,9,9,14,11,13
12210,12439,Zhao Xuebin,25,China PR,Dalian YiFang FC,90000,2000,ST,24,59,...,49,42,14,13,19,12,6,12,13,12
12292,12521,R. Rode,29,Latvia,Waterford FC,50000,1000,CB,26,17,...,39,37,47,61,63,12,15,13,12,10
12304,12533,R. Miura,26,Japan,Júbilo Iwata,50000,1000,GK,12,5,...,14,22,23,16,12,58,54,52,49,48
12327,12556,Sun Kai,27,China PR,Shanghai Greenland Shenhua FC,50000,2000,LB,46,18,...,35,42,53,59,58,7,13,9,9,14
12334,12563,Li Fang,25,China PR,Chongqing Dangdai Lifan FC SWM Team,60000,1000,RB,45,28,...,37,36,64,61,55,14,6,11,6,5
12335,12564,E. Alarcón,25,Argentina,Patronato,50000,2000,GK,13,7,...,12,47,12,10,14,56,55,55,50,52
12353,12582,J. McCombe,35,England,Lincoln City,10000,2000,CB,24,23,...,31,43,51,51,53,6,14,12,11,14
12357,12586,Wen Zhixiang,25,China PR,Henan Jianye FC,50000,1000,GK,16,17,...,21,29,11,13,19,52,45,44,53,60
12368,12597,R. Kawai,39,Japan,Hokkaido Consadole Sapporo,0,1000,CB,39,35,...,43,57,60,59,55,13,6,7,11,9
12400,12629,F. Nicastro,36,Italy,Neuchâtel Xamax,10000,1000,GK,14,9,...,12,46,8,13,14,50,52,58,58,52
12422,12651,T. Warner,44,Trinidad & Tobago,Accrington Stanley,0,1000,GK,19,13,...,17,46,19,15,14,48,56,56,60,44
12438,12667,Xue Yanan,28,China PR,Changchun Yatai FC,40000,2000,RB,39,31,...,43,40,73,47,45,8,11,6,11,8
12446,12675,J. Skov Hansen,25,Denmark,Randers FC,60000,2000,RM,46,41,...,40,44,35,37,36,13,15,6,11,15
12448,12677,S. Phillips,40,England,Yeovil Town,0,1000,GK,13,15,...,13,63,15,12,17,48,54,47,53,46
12537,12766,Zhou Ting,39,China PR,Dalian YiFang FC,10000,1000,CM,45,53,...,49,52,17,45,44,10,12,7,15,6
12550,12779,A. Ekblad,30,Sweden,Dalkurd FF,40000,1000,CB,23,17,...,28,41,45,55,53,13,7,5,7,12
12552,12781,P. Azizi,30,Sweden,Dalkurd FF,40000,1000,CB,28,16,...,28,38,46,56,53,10,6,6,7,10
12561,12790,N. Hatta,32,Japan,Júbilo Iwata,30000,1000,GK,12,6,...,11,24,30,12,13,54,48,45,52,54
12623,12852,T. Nakagawa,25,Japan,Yokohama F. Marinos,40000,1000,RW,40,61,...,64,52,34,10,11,10,11,11,13,9
12682,12911,Wang Xuanhong,28,China PR,Beijing Renhe FC,40000,2000,CM,31,42,...,35,38,62,51,46,10,7,16,12,8
12719,12948,J. Miszczuk,27,Poland,Jagiellonia Białystok,20000,1000,GK,11,11,...,22,22,15,19,17,48,48,49,48,51
12737,12966,A. Suzuki,31,Japan,Yokohama F. Marinos,20000,1000,GK,11,9,...,18,31,13,10,14,49,48,54,52,54
12746,12975,Teng Shangkun,27,China PR,Tianjin TEDA FC,20000,1000,GK,10,8,...,17,58,28,10,13,46,56,55,45,53
12749,12978,M. Mansour,26,Saudi Arabia,Al Batin,30000,2000,LB,36,18,...,33,37,45,54,54,10,8,6,13,13
12767,12996,Sun Qibin,26,China PR,Tianjin Quanjian FC,20000,2000,GK,14,7,...,12,30,46,11,10,50,46,51,48,50
12861,13090,Y. Uchimura,33,Japan,Hokkaido Consadole Sapporo,20000,1000,CAM,51,31,...,33,62,45,48,42,13,15,7,15,15
12873,13102,K. Pilkington,44,England,Cambridge United,0,1000,GK,11,12,...,22,56,15,15,13,45,48,44,49,46

In [4]:
football[(football.Age < football.Age.mean())|
        (football.Club == 'FC Barcelona')]

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
15,15,P. Dybala,24,Argentina,Juventus,89000000,205000,LF,82,84,...,86,84,23,20,20,5,4,4,5,8
16,16,H. Kane,24,England,Tottenham Hotspur,83500000,205000,ST,75,94,...,90,89,56,36,38,8,10,11,14,11
18,18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK,15,14,...,25,69,25,13,10,87,85,88,85,90
20,20,Sergio Busquets,29,Spain,FC Barcelona,51500000,315000,CDM,62,67,...,60,90,90,86,80,5,8,13,9,13
25,25,K. Mbappé,19,France,Paris Saint-Germain,81000000,100000,RM,77,88,...,70,86,34,34,32,13,5,7,11,6
32,32,Coutinho,26,Brazil,FC Barcelona,69500000,340000,LW,79,79,...,70,85,55,54,47,12,7,9,14,6
42,42,S. Umtiti,24,France,FC Barcelona,57000000,205000,CB,69,51,...,61,82,90,89,86,15,10,14,12,15
49,49,Jordi Alba,29,Spain,FC Barcelona,38000000,250000,LB,87,73,...,59,79,72,84,85,13,15,13,6,13
53,53,I. Rakitić,30,Croatia,FC Barcelona,46500000,260000,RCM,84,83,...,82,81,72,74,70,14,11,12,5,9
54,54,Piqué,31,Spain,FC Barcelona,34000000,240000,RCB,57,64,...,69,86,91,86,84,10,11,14,15,8
55,55,L. Sané,22,Germany,Manchester City,61000000,195000,LW,83,81,...,71,78,36,32,35,8,12,9,9,14
56,56,Bernardo Silva,23,Portugal,Manchester City,59500000,180000,RW,85,75,...,68,85,49,44,35,9,10,14,12,9
57,57,Ederson,24,Brazil,Manchester City,41500000,125000,GK,20,14,...,17,70,28,15,8,85,80,91,82,87
60,60,R. Sterling,23,England,Manchester City,56500000,195000,RW,77,77,...,69,77,47,58,54,15,12,12,15,9
77,77,M. Škriniar,23,Slovakia,Inter,46500000,82000,LCB,40,42,...,56,80,92,88,82,10,13,12,8,12
78,78,S. Milinković-Savić,23,Serbia,Lazio,50500000,73000,CM,64,80,...,56,82,75,77,72,7,10,7,16,7
79,79,Marco Asensio,22,Spain,Real Madrid,54000000,215000,RW,82,82,...,62,83,40,42,39,13,9,6,12,10
80,80,N. Fekir,24,France,Olympique Lyonnais,50000000,92000,CAM,83,82,...,81,89,31,37,25,15,9,8,14,15
82,82,J. Kimmich,23,Germany,FC Bayern München,40500000,92000,RCM,90,66,...,44,82,75,81,79,8,15,7,15,15
83,83,Saúl,23,Spain,Atlético Madrid,50500000,77000,RCM,69,78,...,55,83,77,79,76,7,13,12,10,9
96,96,A. Vidal,31,Chile,FC Barcelona,26000000,205000,CAM,76,75,...,81,81,82,87,86,4,2,4,2,4
110,110,D. Sánchez,22,Colombia,Tottenham Hotspur,34000000,105000,RCB,36,40,...,44,75,84,85,88,9,7,10,6,15
111,111,J. Giménez,23,Uruguay,Atlético Madrid,34000000,63000,RCB,47,37,...,38,73,88,86,87,9,11,7,10,15
113,113,A. Laporte,24,France,Manchester City,34000000,135000,LCB,58,45,...,44,77,85,86,87,10,11,5,14,5
114,114,Bruno Fernandes,23,Portugal,Sporting CP,40500000,22000,LCM,84,73,...,81,83,63,66,53,12,14,15,8,14
115,115,N. Süle,22,Germany,FC Bayern München,36500000,84000,CB,30,20,...,32,72,82,85,83,15,7,14,7,15
116,116,A. Martial,22,France,Manchester United,42500000,165000,LW,76,84,...,81,79,38,39,36,9,8,8,15,11
117,117,D. Alli,22,England,Tottenham Hotspur,42500000,115000,LCM,69,83,...,74,86,70,70,63,7,6,9,11,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12866,13095,T. Hillman,17,Wales,Newport County,40000,1000,RM,40,47,...,46,36,18,25,25,14,6,9,10,8
12867,13096,R. Roache,18,Republic of Ireland,Blackpool,70000,1000,ST,32,53,...,55,49,18,16,11,6,9,11,7,12
12868,13097,L. Wahlstedt,18,Sweden,Dalkurd FF,50000,1000,GK,10,7,...,12,28,16,11,10,47,46,50,45,51
12869,13098,J. Williams,17,England,Northampton Town,2300000,1000,CB,25,22,...,32,37,42,51,49,14,11,7,11,8
12870,13099,M. Hurst,22,Scotland,St. Johnstone FC,40000,1000,GK,19,15,...,29,28,12,15,16,45,49,50,50,45
12871,13100,C. Maher,17,Republic of Ireland,Bray Wanderers,50000,1000,RB,45,46,...,33,38,43,49,45,8,10,12,9,10
12872,13101,Y. Góez,18,Colombia,Atlético Nacional,50000,1000,CDM,35,33,...,44,38,44,42,46,9,15,15,8,6
12874,13103,D. Horton,18,England,Lincoln City,40000,1000,CM,33,24,...,37,42,47,49,53,12,5,12,14,15
12875,13104,E. Tweed,19,Republic of Ireland,Derry City,50000,1000,LCM,37,34,...,40,43,39,39,48,6,11,9,5,8
12876,13105,Zhang Yufeng,20,China PR,Beijing Renhe FC,60000,1000,CM,35,29,...,43,39,53,41,51,15,7,14,6,8
12877,13106,C. Ehlich,19,Germany,SpVgg Unterhaching,40000,1000,RB,39,40,...,47,47,40,42,42,13,12,11,15,12
12878,13107,L. Collins,17,Wales,Newport County,350000,1000,CM,41,38,...,36,46,33,38,41,5,12,8,13,10
12879,13108,A. Kaltner,18,Germany,SpVgg Unterhaching,60000,1000,ST,37,48,...,48,37,28,15,22,15,5,14,12,8
12880,13109,L. Watkins,18,England,Cambridge United,60000,1000,CM,32,32,...,34,46,35,44,47,13,7,14,10,8
12881,13110,J. Norville-Williams,18,England,Cambridge United,50000,1000,LB,47,26,...,29,36,45,42,46,15,13,6,14,12
12882,13111,S. Squire,18,England,Cambridge United,50000,1000,CDM,39,36,...,33,38,41,41,44,11,11,8,12,13
12883,13112,N. Fuentes,18,Chile,Unión Española,50000,1000,RB,36,25,...,32,32,41,48,48,6,10,6,12,11
12884,13113,J. Milli,18,Italy,Lecce,50000,1000,GK,10,6,...,16,23,6,10,11,52,52,52,40,44
12885,13114,S. Griffin,18,Republic of Ireland,Waterford FC,350000,1000,CM,35,29,...,35,41,44,37,48,13,14,12,7,13
12886,13115,K. Fujikawa,19,Japan,Júbilo Iwata,60000,1000,CM,31,28,...,44,35,41,44,54,10,12,6,11,8
12887,13116,D. Holland,18,Republic of Ireland,Cork City,60000,1000,CM,44,44,...,49,52,41,47,38,13,6,9,10,15
12888,13117,J. Livesey,18,England,Burton Albion,60000,1000,GK,14,8,...,14,34,15,11,13,46,52,58,42,48
12889,13118,M. Baldisimo,18,Canada,Vancouver Whitecaps FC,70000,1000,CM,31,31,...,36,40,48,49,49,7,7,9,14,15
12890,13119,J. Young,18,Scotland,Swindon Town,450000,1000,ST,28,47,...,58,50,15,17,14,11,15,12,12,11
12891,13120,D. Walsh,18,Republic of Ireland,Waterford FC,60000,1000,RB,22,23,...,38,43,44,47,53,9,10,9,11,13
12892,13121,J. Lundstram,19,England,Crewe Alexandra,1100000,1000,CM,34,38,...,43,45,40,48,47,10,13,7,8,9
12893,13122,N. Christoffersson,19,Sweden,Trelleborgs FF,60000,1000,ST,23,52,...,43,42,22,15,19,10,9,9,5,12
12894,13123,B. Worman,16,England,Cambridge United,60000,1000,ST,25,40,...,55,41,32,13,11,6,5,10,6,13
12895,13124,D. Walker-Rice,17,England,Tranmere Rovers,60000,1000,RW,44,50,...,50,46,20,25,27,14,6,14,8,9
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9

In [5]:
football[(football.Age < football.Age.mean())&
        (football.Club == 'FC Barcelona')].Wage.mean()

77454.54545454546

Задание 1 
Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых выше среднего? Ответ округлите до сотых.

In [6]:
football[football.Wage > football.Wage.mean()].SprintSpeed.mean()

67.56638061585058

Задание 2 
Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых ниже среднего? Ответ округлите до сотых.

In [7]:
football[football.Wage < football.Wage.mean()].SprintSpeed.mean()

62.41425430560645

Задание 3  
Какую позицию (Position) занимает футболист с самой высокой зарплатой (Wage)?

In [9]:
football[football.Wage==football.Wage.max()].Position

0    RF
Name: Position, dtype: object

Задание 4
Сколько пенальти (Penalties) забили бразильские (Nationality, Brazil) футболисты за период, данные о котором представлены в датасете?

In [10]:
football[football.Nationality == 'Brazil'].Penalties.sum()

22789

Задание 5 
Укажите средний возраст (Age) игроков, у которых точность удара головой (HeadingAccuracy) > 50. Ответ округлите до сотых.

In [12]:
football[football.HeadingAccuracy > 50].Age.mean()

25.58771113179944

Задание 6 
Укажите возраст (Age) самого молодого игрока, у которого хладнокровие (Composure) и реакция (Reactions) превышают 90% от максимального значения, представленного в датасете

In [13]:
football[(football.Composure > 0.9*football.Composure.max()) & (football.Reactions > 0.9*football.Reactions.max())].Age.min()

24

Задание 7 
Определите, на сколько средняя реакция (Reactions) самых взрослых игроков (т.е. игроков, чей возраст (Age) равен максимальному) больше средней реакции самых молодых игроков. Ответ округлите до сотых.

In [14]:
football[football.Age == football.Age.max()].Reactions.mean()-football[football.Age == football.Age.min()].Reactions.mean()

22.642857142857146

Задание 8  
Из какой страны (Nationality) происходит больше всего игроков, чья стоимость (Value) превышает среднее значение?

In [21]:
football[(football.Value > football.Value.mean())].Nationality.describe(include=['object'])

count      1747
unique       98
top       Spain
freq        211
Name: Nationality, dtype: object

Задание 9 
Во сколько раз средняя зарплата (Wage) голкипера (Position, GK) с максимальным значением показателя "Рефлексы" (GKReflexes) выше средней зарплаты голкипера с максимальным значением показателя "Владение мячом" (GKHandling). Ответ округлите до сотых.

In [33]:
a=football[(football.Position == 'GK') & (football.GKReflexes==football.GKReflexes.max())].Wage.mean()

In [34]:
b=football[(football.Position == 'GK') & (football.GKHandling==football.GKHandling.max())].Wage.mean()

In [37]:
a/b

2.765957446808511

In [36]:
football[(football.Position == 'GK') & (football.GKReflexes == football.GKReflexes.max())].Wage.mean()/football[(football.Position == 'GK') & (football.GKHandling == football.GKHandling.max())].Wage.mean()

2.765957446808511

Задание 10 
Во сколько раз средняя сила удара (ShotPower) самых агрессивных игроков (игроков с максимальным значением показателя "Агрессивность" (Aggression)) выше силы удара игроков с минимальной агрессией? Ответ округлите до сотых.

In [31]:
football[football.Aggression == football.Aggression.max()].ShotPower.mean()/football[football.Aggression == football.Aggression.min()].ShotPower.mean()

2.076923076923077